### ISSUE TITLE
 environmental issues help~

### ISSUE THREAD

**Issue by ApprenticeYc** [changyanchuan/TrajCL#1]
Hello, I am studying your article "trajcl", and now I am encountering some environmental issues. My graphics card is A10, the base image is pytorch:1.14-cu12.0-py3.8-ubuntu20.04. Now I have created an environment consistent with your version using conda env: Ubuntu 20.04+Python 3.7.7+torch-1.8.1+cu102, but now when I import torch, I encounter a coredump, and have not found a way to fix it yet. I am thinking of using the higher version "pytorch:1.14-cu12.0-py3.8-ubuntu20.04" to run your model, could this work? xiexie for u reply. lol

**Comment by changyanchuan** [comment]
Thank you for your interest to our work.

I am not quite sure about the reason of the core dump error. It may be caused by the cuda libraries, I guess. Yes, py3.8 with pytorch 1.14 should work as well. The code is not necessarily limited to a specific python or torch version actually.

**Comment by ApprenticeYc** [comment]
> �Thank you for your interest to our work.
> 
> I am not quite sure about the reason of the core dump error. It may be caused by the cuda libraries, I guess. Yes, py3.8 with pytorch 1.14 should work as well. The code is not necessarily limited to a specific python or torch version actually.

Thank you very much for your reply; I've resolved the environment issues by using a higher version. I'm also working on trajectory-related research. May I add your contact information?
