### ISSUE TITLE
A question about Similarity Metrics 

### ISSUE THREAD

**Issue by ApprenticeYc** [changyanchuan/TrajCL#2]
Could you please inform me whether you selected the L2 Euclidean distance or the cosine distance when calculating the trajectory embedding vector similarity using faiss? I look forward to your reply.

**Comment by changyanchuan** [comment]
We use L1 distance (cf. the problem statement in Section 3), i.e., faiss.METRIC_L1 with faiss.IndexIVFFlat.

**Comment by ApprenticeYc** [comment]
> We use L1 distance (cf. the problem statement in Section 3), i.e., faiss.METRIC_L1 with faiss.IndexIVFFlat.

Thank you for your response; I overlooked that.
