### ISSUE TITLE
Question about non-GPS datasets

### ISSUE THREAD

**Issue by maaeedee** [changyanchuan/TrajCL#3]
Hi, 
I have a question about using your proposed method on non-GPS datasets, i.e., the Opentraj dataset which is the (x,y) pixel of moving pedestrians. I understand that I need to come up with a new preprocessing file for this new dataset. I'm wondering if there is a specific point or guideline that I can follow for this experiment.

**Comment by changyanchuan** [comment]
Hi. Apologies for my late reply. I just found this issue today while replying to another one. I perhaps missed the github notification email.

We have not tried our method for images. You may start by trying to map image pixels to the grid cells we used, i.e., an image of 300*200 -> a grid cell space of 300*200. However, I have a concern on that TrajCL needs the original GPS coordinates, i.e., real numbers, while trajectories represented as images may not have this kind of features.
